// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGOdI6xmFVLTnhWmr6Z9RQvfn13b0Qg0A',
    appId: '1:268404535960:web:b906074b7fa5a79081d6ed',
    messagingSenderId: '268404535960',
    projectId: 'tik-tok-clone-3b04c',
    authDomain: 'tik-tok-clone-3b04c.firebaseapp.com',
    storageBucket: 'tik-tok-clone-3b04c.appspot.com',
    measurementId: 'G-4NJ8CV6B1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJZ8fz7j7Er2NGl04YdHwUGHNMKMVUhY',
    appId: '1:268404535960:android:c5036ff2e8ecdfb281d6ed',
    messagingSenderId: '268404535960',
    projectId: 'tik-tok-clone-3b04c',
    storageBucket: 'tik-tok-clone-3b04c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh_3qe1-78JVtZ6DM9ij3uKeqA-bV2Bdo',
    appId: '1:268404535960:ios:5c43dcd210e71dce81d6ed',
    messagingSenderId: '268404535960',
    projectId: 'tik-tok-clone-3b04c',
    storageBucket: 'tik-tok-clone-3b04c.appspot.com',
    iosClientId: '268404535960-i860l7e278l0cptlev7eh0gqo540j4n4.apps.googleusercontent.com',
    iosBundleId: 'com.imran.tokTik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh_3qe1-78JVtZ6DM9ij3uKeqA-bV2Bdo',
    appId: '1:268404535960:ios:5c43dcd210e71dce81d6ed',
    messagingSenderId: '268404535960',
    projectId: 'tik-tok-clone-3b04c',
    storageBucket: 'tik-tok-clone-3b04c.appspot.com',
    iosClientId: '268404535960-i860l7e278l0cptlev7eh0gqo540j4n4.apps.googleusercontent.com',
    iosBundleId: 'com.imran.tokTik',
  );
}
